export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  image: string;
  images?: string[];
  category: string;
  isNew?: boolean;
  inStock: boolean;
  dimensions: string;
  material: string;
}

// Configuração de preços por categoria - ALTERE AQUI PARA MUDAR TODOS OS PREÇOS DE UMA CATEGORIA
export const categoryPrices = {
  Vestidos: {
    price: 500.0,
    originalPrice: 650.0,
  },
  Saias: {
    price: 250.0,
    originalPrice: 350.0,
  },
  Calcas: {
    price: 200.0,
    originalPrice: 300.0,
  },
} as const;

export const categories = ["Vestidos", "Saias", "Calças"] as const;

export const products: Product[] = [
  // VESTIDOS
  {
    id: "vestido-1",
    name: "Vestido Branco Elegante",
    description:
      "Vestido clássico em renda filé branca, perfeito para ocasiões especiais. Trabalho artesanal refinado com detalhes únicos.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/branco.jpg",
    category: "Vestidos",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-2",
    name: "Vestido Azul Marinho",
    description:
      "Vestido sofisticado em renda filé azul marinho. Ideal para eventos formais e cerimônias.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/quatro-tons-azul.jpg",
    category: "Vestidos",
    isNew: false,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-3",
    name: "Vestido Floral Colorido",
    description:
      "Vestido vibrante com padrão floral em renda filé multicolorida. Peça única que expressa alegria e criatividade.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/colorido.jpg",
    category: "Vestidos",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-4",
    name: "Vestido Amarelo e Branco",
    description:
      "Vestido delicado em renda filé com combinação harmoniosa de amarelo e branco. Perfeito para ocasiões especiais e eventos diurnos.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/amarelo-branco.jpg",
    category: "Vestidos",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-5",
    name: "Vestido Branco Clássico",
    description:
      "Vestido elegante em renda filé branca tradicional. Design atemporal que nunca sai de moda, ideal para casamentos e batizados.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/branco.jpg",
    category: "Vestidos",
    isNew: false,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-6",
    name: "Vestido Caramelo",
    description:
      "Vestido sofisticado em renda filé na cor caramelo. Tom neutro versátil que combina com qualquer ocasião.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/caramelo.jpg",
    category: "Vestidos",
    isNew: false,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-7",
    name: "Vestido Chocolate",
    description:
      "Vestido elegante em renda filé na cor chocolate. Tom rico e sofisticado, perfeito para eventos noturnos.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/chocolate.jpg",
    category: "Vestidos",
    isNew: false,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-8",
    name: "Vestido Lavanda",
    description:
      "Vestido romântico em renda filé na cor lavanda. Tom delicado e feminino, ideal para ocasiões especiais e românticas.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/lavanda-frente.jpg",
    images: [
      "/images/vestidos/lavanda-frente.jpg",
      "/images/vestidos/lavanta-costas.jpg",
    ],
    category: "Vestidos",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-9",
    name: "Vestido Preto Elegante",
    description:
      "Vestido clássico em renda filé preta. Peça atemporal e sofisticada, perfeita para eventos formais e coquetéis.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/preto.jpg",
    category: "Vestidos",
    isNew: false,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-10",
    name: "Vestido Quatro Tons Azul",
    description:
      "Vestido único em renda filé com quatro tonalidades de azul. Design exclusivo que cria um efeito degradê encantador.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/quatro-tons-azul.jpg",
    category: "Vestidos",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-11",
    name: "Vestido Quatro Tons Rosa",
    description:
      "Vestido romântico em renda filé com quatro tonalidades de rosa. Efeito degradê que transmite delicadeza e feminilidade.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/quatro-tons-rosa.jpg",
    category: "Vestidos",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-12",
    name: "Vestido Quatro Tons Roxo",
    description:
      "Vestido sofisticado em renda filé com quatro tonalidades de roxo. Combinação única que expressa elegância e modernidade.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/quatro-tons-roxo.jpg",
    category: "Vestidos",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-13",
    name: "Vestido Quatro Tons Verde",
    description:
      "Vestido natural em renda filé com quatro tonalidades de verde. Inspirado na natureza, transmite frescor e vitalidade.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/quatro-tons-verde.jpg",
    category: "Vestidos",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-14",
    name: "Vestido Rosa Cru",
    description:
      "Vestido delicado em renda filé na cor rosa cru. Tom suave e neutro, perfeito para diversas ocasiões.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/rosa-cru.jpg",
    category: "Vestidos",
    isNew: false,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-15",
    name: "Vestido Verão",
    description:
      "Vestido leve em renda filé perfeito para o verão. Design fresco e confortável para os dias mais quentes.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/verao-frente.jpg",
    images: [
      "/images/vestidos/verao-frente.jpg",
      "/images/vestidos/verao-costas.jpg",
    ],
    category: "Vestidos",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "vestido-16",
    name: "Vestido Vermelho",
    description:
      "Vestido vibrante em renda filé na cor vermelha. Peça statement que chama atenção e expressa personalidade forte.",
    price: categoryPrices["Vestidos"].price,
    originalPrice: categoryPrices["Vestidos"].originalPrice,
    image: "/images/vestidos/vermelho-frente.jpg",
    images: [
      "/images/vestidos/vermelho-frente.jpg",
      "/images/vestidos/vermelho-costas.jpg",
    ],
    category: "Vestidos",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },

  // SAIAS
  {
    id: "saia-1",
    name: "Saia Bege Clássica",
    description:
      "Saia elegante em renda filé na cor bege. Tom neutro e versátil, perfeita para diversas ocasiões.",
    price: categoryPrices["Saias"].price,
    originalPrice: categoryPrices["Saias"].originalPrice,
    image: "/images/saias/bege.jpg",
    category: "Saias",
    isNew: false,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "saia-2",
    name: "Saia Branca Delicada",
    description:
      "Saia clássica em renda filé branca. Peça atemporal e sofisticada, ideal para ocasiões especiais.",
    price: categoryPrices["Saias"].price,
    originalPrice: categoryPrices["Saias"].originalPrice,
    image: "/images/saias/branco.jpg",
    category: "Saias",
    isNew: false,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "saia-3",
    name: "Saia Colorida Laranja",
    description:
      "Saia vibrante em renda filé com detalhes coloridos em laranja. Peça única que adiciona energia ao look.",
    price: categoryPrices["Saias"].price,
    originalPrice: categoryPrices["Saias"].originalPrice,
    image: "/images/saias/colorida-laranja.jpg",
    category: "Saias",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "saia-4",
    name: "Saia Colorida Preta",
    description:
      "Saia moderna em renda filé com detalhes coloridos em preto. Design contemporâneo e elegante.",
    price: categoryPrices["Saias"].price,
    originalPrice: categoryPrices["Saias"].originalPrice,
    image: "/images/saias/colorida-preta.jpg",
    category: "Saias",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "saia-5",
    name: "Saia Colorida Rosa Bebê",
    description:
      "Saia delicada em renda filé com detalhes em rosa bebê. Tom suave e feminino, perfeito para looks românticos.",
    price: categoryPrices["Saias"].price,
    originalPrice: categoryPrices["Saias"].originalPrice,
    image: "/images/saias/colorida-rosa-bebe.jpg",
    category: "Saias",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "saia-6",
    name: "Saia Colorida Rosa Pink",
    description:
      "Saia vibrante em renda filé com detalhes em rosa pink. Cor marcante que expressa personalidade forte.",
    price: categoryPrices["Saias"].price,
    originalPrice: categoryPrices["Saias"].originalPrice,
    image: "/images/saias/colorida-rosa-pink.jpg",
    category: "Saias",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "saia-7",
    name: "Saia Colorida Verde",
    description:
      "Saia natural em renda filé com detalhes em verde. Inspirada na natureza, transmite frescor e vitalidade.",
    price: categoryPrices["Saias"].price,
    originalPrice: categoryPrices["Saias"].originalPrice,
    image: "/images/saias/colorida-verde.jpg",
    category: "Saias",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "saia-8",
    name: "Saia Laranja Vibrante",
    description:
      "Saia energética em renda filé na cor laranja. Tom quente e alegre, perfeita para destacar sua personalidade.",
    price: categoryPrices["Saias"].price,
    originalPrice: categoryPrices["Saias"].originalPrice,
    image: "/images/saias/laranja.jpg",
    category: "Saias",
    isNew: false,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "saia-9",
    name: "Saia Rosa Bebê",
    description:
      "Saia romântica em renda filé na cor rosa bebê. Tom delicado e suave, ideal para ocasiões especiais.",
    price: categoryPrices["Saias"].price,
    originalPrice: categoryPrices["Saias"].originalPrice,
    image: "/images/saias/rosa-bebe.jpg",
    category: "Saias",
    isNew: false,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "saia-10",
    name: "Saia Rosa Pink",
    description:
      "Saia marcante em renda filé na cor rosa pink. Tom vibrante que chama atenção e expressa confiança.",
    price: categoryPrices["Saias"].price,
    originalPrice: categoryPrices["Saias"].originalPrice,
    image: "/images/saias/rosa-pink.jpg",
    category: "Saias",
    isNew: false,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "saia-11",
    name: "Saia Preta Elegante",
    description:
      "Saia clássica em renda filé preta. Peça atemporal e sofisticada, perfeita para eventos formais e ocasiões especiais.",
    price: categoryPrices["Saias"].price,
    originalPrice: categoryPrices["Saias"].originalPrice,
    image: "/images/saias/preta.jpg",
    category: "Saias",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },

  // CALÇAS
  {
    id: "calca-1",
    name: "Calça Azul Claro",
    description:
      "Calça elegante em renda filé azul claro. Perfeita para o verão, combina sofisticação com frescor e leveza.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/azul-claro.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "calca-2",
    name: "Calça Azul Marinho",
    description:
      "Calça sofisticada em renda filé azul marinho. Ideal para ocasiões formais, oferece elegância e conforto.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/azul.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "calca-3",
    name: "Calça Branco e Azul",
    description:
      "Calça única com detalhes em branco e azul. Design exclusivo que combina tradição e modernidade.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/banco-azul.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "calca-4",
    name: "Calça Branca Clássica",
    description:
      "Calça clássica em renda filé branca. Peça versátil e atemporal, perfeita para diversas ocasiões.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/branca.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "calca-5",
    name: "Calça Chocolate",
    description:
      "Calça em tom chocolate, elegante e sofisticada. Cor neutra que combina com diversos looks.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/chocolate.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "calca-6",
    name: "Calça Colorida Especial",
    description:
      "Calça com padrão colorido único. Peça especial para quem busca originalidade e estilo diferenciado.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/colorido.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "calca-7",
    name: "Calça Cru Natural",
    description:
      "Calça em tom cru natural. Elegância sutil e sofisticada, perfeita para looks despojados e chiques.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/cru.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "calca-8",
    name: "Calça Rosa Dupla",
    description:
      "Calça com detalhes em dois tons de rosa. Design exclusivo que expressa feminilidade e delicadeza.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/dois-rosas.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "calca-9",
    name: "Calça Laranja Vibrante",
    description:
      "Calça em tom laranja vibrante. Perfeita para quem gosta de cores marcantes e looks cheios de personalidade.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/laranja.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "calca-10",
    name: "Calça Preta Elegante",
    description:
      "Calça clássica em renda filé preta. Peça coringa do guarda-roupa, elegante e versátil para todas as ocasiões.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/preto.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "calca-11",
    name: "Calça Rosa Claro",
    description:
      "Calça em rosa claro delicado. Feminina e suave, ideal para looks românticos e sofisticados.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/rosa-claro.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "calca-12",
    name: "Calça Rosa Tradicional",
    description:
      "Calça em rosa tradicional. Cor clássica e feminina, perfeita para diversas ocasiões especiais.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/rosa.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "calca-13",
    name: "Calça Verde Ciano",
    description:
      "Calça em verde ciano exclusivo. Cor diferenciada que traz modernidade e frescor ao visual.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/verde-ciano.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
  {
    id: "calca-14",
    name: "Calça Verde Clássica",
    description:
      "Calça em verde clássico. Cor da natureza que transmite tranquilidade e elegância natural.",
    price: categoryPrices["Calcas"].price,
    originalPrice: categoryPrices["Calcas"].originalPrice,
    image: "/images/calcas/verde.jpg",
    category: "Calças",
    isNew: true,
    inStock: true,
    dimensions: "Tamanho único - veste do P ao G",
    material: "Fio de algodão",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Maria Silva",
    location: "São Paulo, SP",
    comment:
      "Os vestidos de renda filé são lindíssimos! A qualidade é excepcional e o caimento perfeito. Recomendo muito!",
    rating: 5,
  },
  {
    id: 2,
    name: "Ana Costa",
    location: "Rio de Janeiro, RJ",
    comment:
      "Comprei um conjunto de saia e blusa em renda filé e ficou perfeito! O trabalho artesanal é impecável e muito elegante.",
    rating: 5,
  },
  {
    id: 3,
    name: "Carla Oliveira",
    location: "Belo Horizonte, MG",
    comment:
      "Atendimento excelente! Tenho vestidos e saias de renda filé e sempre fico satisfeita com a qualidade única.",
    rating: 5,
  },
  {
    id: 4,
    name: "Fernanda Santos",
    location: "Fortaleza, CE",
    comment:
      "Usei meu vestido de renda filé na praia e recebi muitos elogios! Leve, fresco e elegante, perfeito para o verão.",
    rating: 5,
  },
  {
    id: 5,
    name: "Juliana Almeida",
    location: "Salvador, BA",
    comment:
      "Minha saia de renda filé é perfeita para usar sobre o biquíni! Estilosa e confortável para os dias de praia.",
    rating: 5,
  },
  {
    id: 6,
    name: "Patrícia Lima",
    location: "Natal, RN",
    comment:
      "Adoro usar meus conjuntos de renda filé como saída de praia. São únicos e sempre chamam atenção no resort!",
    rating: 5,
  },
  {
    id: 7,
    name: "Camila Ferreira",
    location: "Florianópolis, SC",
    comment:
      "O vestido branco de renda filé é minha peça favorita para o verão! Uso na praia, na piscina e até para jantar.",
    rating: 5,
  },
  {
    id: 8,
    name: "Renata Souza",
    location: "Búzios, RJ",
    comment:
      "Trabalho com moda praia e sempre indico os vestidos e saias de renda filé. Minhas clientes adoram a qualidade e o estilo!",
    rating: 5,
  },
  {
    id: 9,
    name: "Isabela Rodrigues",
    location: "Maceió, AL",
    comment:
      "Meu conjunto de renda filé é perfeito para casamentos na praia! Recebo elogios onde quer que eu vá.",
    rating: 5,
  },
];
