version: "3.8"

services:
  renda-file-catalogo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GITHUB_PAGES=false
    container_name: renda-file-catalogo
    restart: unless-stopped

  # Versão para desenvolvimento
  renda-file-catalogo-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - GITHUB_PAGES=false
    volumes:
      - .:/app
      - /app/node_modules
    container_name: renda-file-catalogo-dev
    restart: unless-stopped
    profiles:
      - dev
